---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pink-api
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: pink-api
    spec:
      containers:
      - name: pink-api
        image: brentlangston/example-api:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8000
      nodeSelector:
        nodegroup-type: api-workloads
