apiVersion: v1
kind: Service
metadata:
  name: pink-api
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /
spec:
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: pink-api
