---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yellow-api
spec:
  selector:
    matchLabels:
      app: yellow-api
  template:
    metadata:
      labels:
        app: yellow-api
    spec:
      containers:
      - env:
        - name: msg
          value: This is the YELLOW api!
        image: brentlangston/example-api:latest
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: "0.5"
        imagePullPolicy: "Always"
        name: yellow-api
        ports:
        - containerPort: 8000
      nodeSelector:
        nodegroup-type: api-workloads
