---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yellow-api
spec:
  selector:
    matchLabels:
      app: yellow-api
  template:
    metadata:
      labels:
        app: yellow-api
    spec:
      containers:
      - name: yellow-api
        image: 048815747800.dkr.ecr.us-east-1.amazonaws.com/examp-examp-793dcbtqqe9j:cc23259
        env:
        - name: msg
          value: "yellow-api! "
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: "0.5"
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8000
      nodeSelector:
        nodegroup-type: api-workloads
