apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: alb-ingress-rules
  namespace: default
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: 2
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: 5
    alb.ingress.kubernetes.io/target-group-attributes: deregistration_delay.timeout_seconds=30
  labels:
    app: alb-ingress-rules
spec:
  rules:
    - http:
        paths:
          - path: /blue/*
            backend:
              serviceName: blue-api
              servicePort: 8000
          - path: /yellow/*
            backend:
              serviceName: yellow-api
              servicePort: 8000
          - path: /pink/*
            backend:
              serviceName: pink-api
              servicePort: 8000
          - path: /red/*
            backend:
              serviceName: red-api
              servicePort: 8000
