apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: demo
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: podinfo
  chart:
    git: https://github.com/stefanprodan/podinfo
    name: demo
    ref: 3.0.0
    path: charts/podinfo
