---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: grafana
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: grafana
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: grafana
    version: 3.8.15
  values:
    service:
      type: LoadBalancer
    persistence:
        enabled: true
    persistence.storageClassName: efs
    admin.password: "mysecret"
    datasources: 
       datasources.yaml:
            apiVersion: 1
            datasources:
            - name: Prometheus
              type: prometheus
              url: http://prometheus-server.prometheus.svc.cluster.local
              access: proxy
              isDefault: true
    sidecar:
      datasources:
        enabled: true
        label: grafana_datasource
      dashboards:
        enabled: true
        label: grafana_dashboard
    dashboards:
      default:
        k8s-cluster-monitoring:
          gnetId: 10000
          revision: 1
          datasource: Prometheus
        k8s-cluster:
          gnetId: 10670
          revision: 4
          datasource: Prometheus
        k8s-cluster-details:
          gnetId: 10856
          revision: 1
          datasource: Prometheus
        k8s-deployment:
          gnetId: 10858
          revision: 1
          datasource: Prometheus
        k8s-all:
          gnetId: 10185
          revision: 1
          datasource: Prometheus
        k8s-cluster-health:
          gnetId: 5312
          revision: 1
          datasource: Prometheus
        k8s-cluster-usage:
          gnetId: 315
          revision: 3
          datasource: Prometheus
