apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: red-api
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: red-api
  minReplicas: 3
  maxReplicas: 25
  targetCPUUtilizationPercentage: 75
