---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: red-api
spec:
  selector:
    matchLabels:
      app: red-api
  template:
    metadata:
      labels:
        app: red-api
    spec:
      containers:
      - name: red-api
        image: k8s.gcr.io/hpa-example:latest
        resources:
          requests:
            cpu: "500m"
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80
      nodeSelector:
        nodegroup-type: api-workloads
