---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: red-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: red-api
  template:
    metadata:
      labels:
        app: red-api
    spec:
      containers:
      - env:
        - name: msg
          value: This is the RED api!
        image: brentlangston/example-api:latest
        imagePullPolicy: "Always"
        name: red-api
        ports:
        - containerPort: 8000
      nodeSelector:
        nodegroup-type: api-workloads
