apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "example-kafka-consumer-deployment"
  namespace: default
spec:
  replicas: 35
  template:
    metadata:
      labels:
        app: "example-kafka-consumer"
    spec:
      containers:
      - image: progrium/stress:latest
        command: ["stress"]
        resources:
          limits:
            cpu: 1
          requests:
            cpu: 1
        imagePullPolicy: Always
        name: "example-kafka-consumer"
