apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "example-kafka-consumer-deployment"
  namespace: default
spec:
  replicas: 35
  template:
    metadata:
      labels:
        app: "example-kafka-consumer"
    spec:
      containers:
      - image: progrium/stress:latest
        command: ["stress"]
        args: ["--cpu 2 --io 1 --vm 2 --hdd 4 --hdd-bytes 10M"]
        resources:
          limits:
            cpu: 1
          requests:
            cpu: 1
        imagePullPolicy: Always
        name: "example-kafka-consumer"
