apiVersion: v1
kind: Service
metadata:
  name: blue-api
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: blue-api
