apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: blue-api
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: blue-api
  minReplicas: 3
  maxReplicas: 50
  targetCPUUtilizationPercentage: 75
