---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blue-api
  template:
    metadata:
      labels:
        app: blue-api
    spec:
      containers:
      - env:
        - name: msg
          value: This is the BLUE api!
        image: brentlangston/example-api:latest
        imagePullPolicy: Always
        name: blue-api
        ports:
        - containerPort: 8000
      nodeSelector:
        nodegroup-type: api-workloads
