---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-api
spec:
  selector:
    matchLabels:
      app: blue-api
  template:
    metadata:
      labels:
        app: blue-api
    spec:
      containers:
      - name: blue-api
        image: 048815747800.dkr.ecr.us-east-1.amazonaws.com/examp-examp-793dcbtqqe9j:b927d55
        env:
        - name: msg
          value: "blue-api! "
        resources:
          limits:
            cpu: "1000m"
          requests:
            cpu: "200m"
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8000
      nodeSelector:
        nodegroup-type: api-workloads
