---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-api
spec:
  template:
    spec:
      containers:
      - name: blue-api
        image: brentlangston/example-api:latest
        env:
        - name: msg
          value: "This is the BLUE api!"
