---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-api
spec:
  selector:
    matchLabels:
      app: blue-api
  template:
    metadata:
      labels:
        app: blue-api
    spec:
      containers:
      - name: blue-api
        image: brentlangston/example-api:latest
        resources:
          limits:
            cpu: "1000m"
          requests:
            cpu: "200m"
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8000
      nodeSelector:
        nodegroup-type: api-workloads
