---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pink-api
spec:
  selector:
    matchLabels:
      app: pink-api
  template:
    metadata:
      labels:
        app: pink-api
    spec:
      containers:
      - name: pink-api
        image: brentlangston/example-api:latest
        env:
        - name: msg
          value: "pink-api! "
        resources:
          limits:
            cpu: "200m"
          requests:
            cpu: "100m"
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8000
      nodeSelector:
        nodegroup-type: api-workloads
