apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: demo
spec:
  releaseName: podinfo
  chart:
    repository: https://github.com/stefanprodan/podinfo
    name: demo
    ref: 3.0.0
    path: charts/podinfo
